# æ¨é€è§¦å‘è„šæœ¬
name: Publish And Deploy nuxt Demo
on:
  push:
    branches:
      - devloper
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ä¸‹è½½æºç 
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master

      # æ‰“åŒ…æ„å»º
      #- name: Install and Build ğŸ”§
      #  uses: actions/setup-node@master
      #- run: npm install
      #- run: npm run build

      # å‘å¸ƒé¡µé¢
      - name: Build ğŸ›ï¸ and Deploy ğŸš€
      # uses: JamesIves/github-pages-deploy-action@master
      - uses: kappa0923/nuxtjs-generate-action@master
      - uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: devloper # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          BUILD_SCRIPT: npm install && npm run-script build
